# osm_poi_reader.py
# osm_poi.pyで出力したPickleファイルを読み込むサンプル

"""
This program is a sample for reading Pickle files generated by osm_poi.py.
It uses Streamlit to create a web application that allows users to upload Pickle files and display their contents as DataFrames.
"""

# Streamlit: https://www.streamlit.io/
import streamlit as st

# General libraries
import pickle

# ファイル名
filenames = ['osm_poi.pickle', '']

# Initialize Streamlit
def init():
    st.set_page_config(page_title="OSM POI Reader", page_icon=":earth_americas:", layout="wide")
    st.title("OpenStreetMap POI Reader")

# Main function
def main():
    # Initialize Streamlit
    init()

    # ファイルアップロード
    uploaded_files = st.file_uploader("Choose Pickle files", accept_multiple_files=True)
    if uploaded_files is not None:
        # アップロードされたファイルそれぞれについてバイト列を取得
        for uploaded_file in uploaded_files:
            bytes_data = uploaded_file.read()

            # バイト列からDataFrameを復元
            df = pickle.loads(bytes_data)
            
            # DataFrameを表示
            st.subheader(uploaded_file.name)
            st.dataframe(df)
    
    df.to_csv("")

if __name__ == '__main__':
    main()
